SELECT CHE.COMPANY_NAME,
	CHE.ADDRESS_POST_CODE
FROM COMPANY_SPONSOR CS
JOIN PDFSPONSOR PS ON CS.PDF_SPONSOR_ID = PS.ID
JOIN COMPANY_HOUSE_ENTRY CHE ON CHE.ID = CS.COMPANY_HOUSE_ENTRY_ID
WHERE CS.NAME_MATCHES IS TRUE;