package com.janaldous.sponsorship.domain.core;

public enum ApplicationStatus {

	APPLIED, IN_PROGRESS, REJECTED, DEFERRED, CHECKED_NO_WEBSITE, CHECKED_NO_CAREERS_PAGE, CHECKED_CAREERS_PAGE_NO_JOBS,
	CHECKED_LINKED_IN_NO_JOBS, CHECKED_CAREERS_PAGE_NOT_QUALIFIED, NOT_TECH_COMPANY, NO_LONDON_TECH_JOBS,
	ADDED_TO_APPLICATION_QUEUE;

}
