package com.janaldous.sponsorship.domain.core;

public enum ApplicationStatus {

	APPLIED, IN_PROGRESS, REJECTED, DEFERRED, CHECKED_NO_WEBSITE, CHECKED_NO_CAREERS_PAGE, CHECKED_CAREERS_PAGE_NO_JOBS,
	CHECKED_LINKED_IN_NO_JOBS, CHECKED_CAREERS_PAGE_NOT_QUALIFIED;

}
