package com.janaldous.sponsorship.domain.core;

public enum FetchDataStatus {

	MULTIPLE_RESULT, SUCCESS, FAILED, NO_RESULT, MULTIPLE_RESULT_MATCH_LOCALITY, MULTIPLE_RESULT_MATCH_NORMALIZED,
	MULTIPLE_RESULT_MATCH_FUZZY;

}
